### PR TITLE
feat: add destructured array ignore pattern

### PR DESCRIPTION
**Pull request by vinteo**
Add destructured array ignore pattern  to match the arguments ignore pattern

### CODE REVIEW

**Review by pphminions — APPROVED** [review]
LGTM ✏️

**Review by bchew — APPROVED** [review]

**Review by glenkurniawan-adslot — APPROVED** [review]

**Review by romi-h — APPROVED** [review]

**Comment by xiaofan2406** [comment]
for array we can do

```js
const [, theOneToUse] = arr;
```

we dont need to 
```js
const [_theOneToIgnore, theOneToUse] = arr;
```

**Comment by vinteo** [comment]
> for array we can do
> 
> ```js
> const [, theOneToUse] = arr;
> ```
> 
> we dont need to
> 
> ```js
> const [_theOneToIgnore, theOneToUse] = arr;
> ```

TIL lol, we discussed this in a tech meeting and no one was aware of this syntax. I guess it doesn't harm to get it in anyway?

**Comment by vinteo** [comment]
after discussion, decided not to go ahead with this

**Pull request closed without merging**
